name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DROPLET_IP: ${{ secrets.DROPLET_IP }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Load deployment configuration
        run: |
          if [ -f .env.deploy ]; then
            export $(cat .env.deploy | grep -v '^#' | xargs)
          fi
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ env.SSH_PRIVATE_KEY }}
          known_hosts: 'placeholder'
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ env.DROPLET_IP }} >> ~/.ssh/known_hosts
      
      - name: Deploy to Digital Ocean
        run: |
          ssh ${{ env.SSH_USER }}@${{ env.DROPLET_IP }} '
            cd /var/www/o2 &&
            sudo -u www-data git pull origin main &&
            chmod +x deploy_setup.sh &&
            sudo ./deploy_setup.sh
          ' 