name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'placeholder'
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts
      
      - name: Deploy to Digital Ocean
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }} '
            cd /var/www/o2 &&
            sudo -u www-data git pull origin main &&
            sudo -u www-data /var/www/o2/venv/bin/pip install -r requirements.txt &&
            sudo systemctl restart o2
          ' 