name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DROPLET_IP: ${{ secrets.DROPLET_IP }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Load deployment configuration
        run: |
          if [ -f .env.deploy ]; then
            export $(cat .env.deploy | grep -v '^#' | xargs)
          fi
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ env.SSH_PRIVATE_KEY }}
          known_hosts: 'placeholder'
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ env.DROPLET_IP }} >> ~/.ssh/known_hosts
      
      - name: Deploy to Digital Ocean
        run: |
          ssh ${{ env.SSH_USER }}@${{ env.DROPLET_IP }} '
            # Install Docker if not installed
            if ! command -v docker &> /dev/null; then
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
              sudo usermod -aG docker $USER
            fi

            # Install Docker Compose if not installed
            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Deploy application
            cd /var/www/o2 &&
            sudo -u www-data git pull origin main &&
            docker-compose down &&
            docker-compose build --no-cache &&
            docker-compose up -d
          ' 